export { createDatabaseClient, type DatabaseClient } from "./client.js";
export {
  claimBackgroundJob,
  heartbeatBackgroundJob,
  InjectedJobCrash,
  JobCancellationRequestedError,
  JobLeaseLostError,
  makeBackgroundJobRetryDue,
  recordBackgroundJobStage,
  recoverExpiredBackgroundJobLease,
  runIdempotentJobHandler,
  throwIfBackgroundJobCancellationRequested,
  type JobClaimResult,
  type JobCrashPoint,
  type JobDatabaseExecutor,
  type JobHandlerExecutionContext,
  type JobHandlerRunResult,
  type TransactionalJobResult,
} from "./job-execution.js";
export {
  cancelBackgroundJob,
  isSafeProcessingCancellationStage,
  retryBackgroundJob,
  safeProcessingCancellationStages,
  type CancelJobOptions,
  type JobOperationResult,
  type JobOperationTelemetry,
  type JobOperatorContext,
  type ManualRetryJob,
  type ManualRetryOptions,
  type ManualRetryPrerequisiteResult,
} from "./job-operations.js";
export {
  loadJobDiagnosticDetail,
  loadJobDiagnosticList,
  type JobActionEligibility,
  type JobActionUnavailableReason,
  type JobDiagnosticAttempt,
  type JobDiagnosticDetail,
  type JobDiagnosticFilters,
  type JobDiagnosticList,
  type JobDiagnosticListItem,
  type JobUsageSummary,
} from "./job-diagnostics.js";
export {
  reconcileBackgroundJobs,
  type CleanupDebtOutcome,
  type JobCleanupDebtHook,
  type JobReconciliationTelemetry,
  type JobResultInspection,
  type ReconcileBackgroundJobsOptions,
  type ReconcileBackgroundJobsResult,
  type ReconciliationJob,
} from "./job-reconciliation.js";
export {
  enqueueBackgroundJob,
  enqueueBackgroundJobInTransaction,
  reconcileJobOutbox,
  type DispatchTelemetry,
  type EnqueueBackgroundJobInput,
  type EnqueueBackgroundJobResult,
  type ReconcileJobOutboxOptions,
  type ReconcileJobOutboxResult,
} from "./background-jobs.js";
export {
  loadWorkspaceDashboardFoundation,
  type WorkspaceDashboardFoundation,
} from "./dashboard.js";
export {
  authoriseOidcIdentity,
  findActiveAdminPrincipal,
  findActiveSessionPrincipal,
  parseSessionPrincipal,
  setInternalUserStatus,
  signInDenialReasons,
  type SessionPrincipal,
  type SignInDecision,
  type SignInDenialReason,
  type VerifiedOidcIdentity,
} from "./auth.js";
export { requireWorkspaceResource, WorkspaceResourceNotFoundError } from "./authorisation.js";
export {
  CredentialEncryptionError,
  decodeMasterKey,
  decryptCredential,
  encryptCredential,
  hashGrantedScopes,
  scopeHashesMatch,
  type CredentialEncryptionContext,
  type SealedCredential,
} from "./credential-encryption.js";
export { createId, isUuidV7 } from "./id.js";
export {
  commitInstagramDisconnect,
  instagramAccountResourceType,
  instagramDisconnectedAction,
  instagramRevocationOutcomes,
  listInstagramAccountSummaries,
  type InstagramAccountSummary,
  type InstagramDisconnectResult,
  type InstagramRevocationOutcome,
} from "./instagram-account.js";
export {
  instagramSyncRunActive,
  listInstagramAccountsDueForSync,
  listInstagramPostsDueForSnapshot,
  listInstagramSnapshotCoverage,
  type InstagramAccountDueForSync,
  type InstagramPostDueForSnapshot,
} from "./instagram-scheduling.js";
export {
  instagramSnapshotValueSelect,
  listInstagramMetricSnapshots,
  readInstagramSnapshotObservations,
  recordInstagramMetricSnapshot,
  type InstagramSnapshotCommit,
  type InstagramSnapshotInput,
  type InstagramSnapshotSummary,
  type InstagramSnapshotValueRow,
} from "./instagram-insights.js";
export {
  activateAnalyticsRun,
  analyticsDebounceMs,
  analyticsRunFailureCodes,
  createRunInputFingerprint,
  failAnalyticsRun,
  findActiveAnalyticsRun,
  findActiveRunFingerprint,
  listAccountsDueForAnalytics,
  markAnalyticsDirty,
  startAnalyticsRun,
  type ActivationResult,
  type ActiveRunSummary,
  type AnalyticsRunFailureCode,
  type DueAccount,
  type StartedRun,
} from "./analytics-runs.js";
export {
  grantWorkspaceMember,
  isApprovedWorkspaceEmail,
  memberGrantOutcomes,
  normaliseMemberEmail,
  type GrantMemberResult,
  type MemberGrantOutcome,
  type MemberRole,
} from "./workspace-members.js";
export {
  calculateFeatureFamily,
  createStatisticFingerprint,
  maximumPooledSourceShare,
  storeFeatureStatistics,
  type CalculatedComparison,
  type FeatureComparisonCandidate,
  type FeatureObservation,
  type FeatureStatisticRequest,
} from "./feature-statistics.js";
export {
  analysisRequestRefusals,
  requestPostAnalysis,
  type AnalysisRequestOutcome,
  type AnalysisRequestRefusal,
} from "./analysis-request-command.js";
export {
  analysisExistsForJob,
  analysisJobResourceType,
  createAnalysisJob,
  findAnalysisJobForBackgroundJob,
  findAnalysisSourceAsset,
  publishPostAnalysis,
  recordAnalysisProviderFile,
  recordAnalysisStage,
  type AnalysisInputsForRun,
  type AnalysisJobInputs,
  type AnalysisJobRecord,
  type PublishAnalysisInput,
  type PublishAnalysisResult,
} from "./post-analysis.js";
export {
  cohortPostLimit,
  comparePostToCohort,
  loadCohort,
  loadPostMetricValue,
  type Cohort,
  type CohortMember,
  type CohortRequest,
} from "./analytics-cohorts.js";
export {
  isConfidenceClass,
  isDerivedMetric,
  listPublishedTrendScopes,
  listTrendFeaturePaths,
  loadAccountTrends,
  loadTrendDetail,
  trendPageSize,
  type TrendCalculation,
  type TrendContributor,
  type TrendDetail,
  type TrendList,
  type TrendListFilters,
  type TrendListItem,
} from "./analytics-trends.js";
export {
  buildStrategyManifest,
  loadStrategyEvidenceCandidates,
  strategyContractColumns,
  writeStrategyEvidence,
  type FrozenStrategyManifest,
  type StrategyEvidenceCandidates,
  type StrategyEvidenceCounts,
  type StrategyEvidenceRequest,
} from "./strategy-evidence.js";
export {
  listStrategyGenerations,
  loadCurrentStrategy,
  loadStrategyGeneration,
  strategyHistoryLimit,
  type StrategyDetail,
  type StrategyEvidenceEntry,
  type StrategySummary,
} from "./strategy-read.js";
export {
  failStrategyGeneration,
  findStrategyGenerationForJob,
  publishStrategyGeneration,
  recordStrategyStage,
  strategyResultExistsForJob,
  type FrozenStrategyGeneration,
  type PublishStrategyInput,
  type PublishStrategyResult,
} from "./strategy-generation.js";
export {
  previewStrategyRequest,
  requestStrategyGeneration,
  strategyDefaultPeriodDays,
  strategyPooledResourceType,
  type StrategyRequestInput,
  type StrategyRequestOutcome,
  type StrategyRequestPreview,
} from "./strategy-request-command.js";
export {
  chatContextSources,
  loadChatContext,
  type ChatContextResult,
  type ChatContextScope,
  type ChatContextSource,
} from "./chat-context.js";
export {
  appendChatAnswer,
  appendChatQuestion,
  chatSessionMessageLimit,
  chatWorkspaceHourlyTurnLimit,
  countRecentChatQuestions,
  createChatSession,
  deleteChatSession,
  listChatSessions,
  loadChatConversation,
  renameChatSession,
  toChatHistory,
  type AppendedChatMessage,
  type ChatAnswerRecord,
  type ChatConversation,
  type ChatMessageRecord,
  type ChatSessionSummary,
} from "./chat-sessions.js";
export {
  analyticsFeatures,
  analyticsPostLimit,
  buildFeatureRequests,
  loadAnalyticsInputs,
  loadBestAnalyticsInputs,
  type AnalyticsFeature,
  type AnalyticsInputPost,
  type AnalyticsInputRequest,
  type AnalyticsInputSet,
  type AnalyticsWindowSelection,
} from "./analytics-features.js";
export {
  instagramPostPageSize,
  instagramPostSearchLimit,
  isInstagramMediaKind,
  loadInstagramPostList,
  sourceVideoStates,
  type InstagramPostList,
  type InstagramPostListFilters,
  type InstagramPostListItem,
  type SourceVideoState,
} from "./instagram-post-list.js";
export {
  listInstagramCredentialsDueForMaintenance,
  loadInstagramConnectionHealth,
  loadInstagramCredentialForMaintenance,
  purgedCredentialCiphertext,
  recordInstagramCredentialValidation,
  requireInstagramReauthorisation,
  rotateInstagramCredential,
  type InstagramConnectionHealth,
  type InstagramCredentialDue,
  type InstagramCredentialMaintenanceRecord,
} from "./instagram-token.js";
export {
  commitInstagramMediaPage,
  completeInstagramSyncRun,
  failInstagramSyncRun,
  findInstagramPostByProviderMediaId,
  findInstagramSyncRun,
  instagramPostResourceType,
  instagramPostSafeSelect,
  instagramSyncRunSucceededForJob,
  listInstagramPosts,
  startInstagramSyncRun,
  type CommitInstagramMediaPageInput,
  type InstagramMediaPageCommit,
  type InstagramPostSummary,
  type StartInstagramSyncRunInput,
} from "./instagram-media.js";
export {
  createWorkspaceRepositories,
  withWorkspaceTransaction,
  type AuditActor,
  type WorkspaceRepositories,
} from "./repositories.js";
export {
  closeVideoUploadIntent,
  createImportedVideoAsset,
  createVideoAsset,
  createVideoUploadIntent,
  findPendingVideoUploadIntentForPost,
  findVideoAssetForImportJob,
  findVideoAssetForIntent,
  findVideoAssetForValidation,
  findVideoUploadIntent,
  listExpiredVideoUploadIntents,
  listPurgeableVideoAssets,
  markVideoAssetPurged,
  recordVideoAssetValidation,
  uploadIntentAbortedAction,
  uploadIntentCompletedAction,
  uploadIntentExpiredAction,
  uploadIntentInitiatedAction,
  videoAssetResourceType,
  videoUploadIntentResourceType,
  type CreateImportedVideoAssetInput,
  type CreateUploadIntentInput,
  type CreateVideoAssetInput,
  type ExpiredUploadIntent,
  type PurgeableVideoAsset,
  type RecordVideoAssetValidationInput,
  type VideoAssetForValidation,
  type VideoAssetRecord,
  type VideoUploadIntentRecord,
} from "./video-upload.js";
export { createWorkspaceContext, type WorkspaceContext } from "./workspace-context.js";
