import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { queueDefinitions } from "@studio-parallel/domain";
import { describe, expect, it } from "vitest";

/**
 * Every migration has to be SQL, all the way down.
 *
 * This exists because one was not. A migration generated by redirecting
 * `prisma migrate diff --script` to a file picked up the config's target banner,
 * which `prisma.config.ts` prints to stdout rather than stderr, and the banner
 * became line 1 of the script. `migrate deploy` then failed with a syntax error
 * at the first token, on `main` and against the deployed database, which records
 * a failed migration and refuses every later one until it is resolved by hand.
 *
 * Reviewing the diff did not catch it: the SQL below the banner was correct, and
 * the generated body is what a reader checks. So the check is mechanical.
 */

const migrationsDirectory = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "prisma",
  "migrations",
);

function migrationFiles(): readonly string[] {
  return (
    readdirSync(migrationsDirectory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      // Prisma applies migrations in name order, so the last definition of a
      // constraint in this order is the one the database ends up with.
      .sort()
      .map((name) => join(migrationsDirectory, name, "migration.sql"))
  );
}

/** A statement, a comment, or nothing. Anything else is not SQL. */
const sqlStart =
  /^\s*(--|\/\*|ALTER\b|BEGIN\b|COMMENT\b|CREATE\b|DELETE\b|DO\b|DROP\b|GRANT\b|INSERT\b|REVOKE\b|SET\b|TRUNCATE\b|UPDATE\b|WITH\b)/iu;

describe("migration files", () => {
  it("finds the migrations to check, so an empty glob cannot pass silently", () => {
    expect(migrationFiles().length).toBeGreaterThan(0);
  });

  it.each(migrationFiles())("%s starts with SQL", (file) => {
    const first = readFileSync(file, "utf8")
      .split("\n")
      .map((line) => line.trim())
      .find((line) => line.length > 0);

    expect(first ?? "").toMatch(sqlStart);
  });

  it.each(migrationFiles())("%s carries no tool banner on any line", (file) => {
    // The banner names the connection target, so it would also leak a host into
    // version control if one ever reached a later line.
    expect(readFileSync(file, "utf8")).not.toMatch(/^Prisma target:/mu);
  });
});

/**
 * The queue allowlist is written down twice, so the two copies are compared.
 *
 * `queueDefinitions` is what application code validates against; these check
 * constraints are what the database enforces. A queue added to the first and
 * not the second passes every in-process guard and then fails the insert, which
 * the enqueue reports as a generic dependency failure with the constraint name
 * discarded. That is what happened to `instagram.media.import`: the request
 * surfaced as "the video could not be requested", nothing was written, and
 * nothing pointed at the schema.
 *
 * Checked here rather than only against a live database because Prisma cannot
 * express a check constraint, so `db:drift:check` is structurally blind to it,
 * and because this is the copy a reviewer is least likely to remember.
 */
const queueNameConstraints = ["background_jobs_queue_name_check", "job_outbox_queue_name_check"];

/** The names in the last definition of one constraint, in migration order. */
function constrainedQueueNames(constraint: string): readonly string[] {
  const definition = new RegExp(
    `ADD CONSTRAINT "${constraint}" CHECK \\("queue_name" IN \\(([^)]*)\\)\\)`,
    "gu",
  );
  let latest: string | undefined;

  for (const file of migrationFiles()) {
    for (const match of readFileSync(file, "utf8").matchAll(definition)) latest = match[1];
  }

  return [...(latest ?? "").matchAll(/'([^']+)'/gu)].map((match) => match[1] ?? "");
}

describe("background queue names", () => {
  it.each(queueNameConstraints)(
    "%s allows every declared queue, and nothing else",
    (constraint) => {
      // Order is compared as well as membership: the two lists are read side by
      // side when a queue is added, and one that reorders is harder to check.
      expect(constrainedQueueNames(constraint)).toEqual(queueDefinitions.map(({ name }) => name));
    },
  );
});
