import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

/**
 * Every migration has to be SQL, all the way down.
 *
 * This exists because one was not. A migration generated by redirecting
 * `prisma migrate diff --script` to a file picked up the config's target banner,
 * which `prisma.config.ts` prints to stdout rather than stderr, and the banner
 * became line 1 of the script. `migrate deploy` then failed with a syntax error
 * at the first token, on `main` and against the deployed database, which records
 * a failed migration and refuses every later one until it is resolved by hand.
 *
 * Reviewing the diff did not catch it: the SQL below the banner was correct, and
 * the generated body is what a reader checks. So the check is mechanical.
 */

const migrationsDirectory = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "prisma",
  "migrations",
);

function migrationFiles(): readonly string[] {
  return readdirSync(migrationsDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(migrationsDirectory, entry.name, "migration.sql"));
}

/** A statement, a comment, or nothing. Anything else is not SQL. */
const sqlStart =
  /^\s*(--|\/\*|ALTER\b|BEGIN\b|COMMENT\b|CREATE\b|DELETE\b|DO\b|DROP\b|GRANT\b|INSERT\b|REVOKE\b|SET\b|TRUNCATE\b|UPDATE\b|WITH\b)/iu;

describe("migration files", () => {
  it("finds the migrations to check, so an empty glob cannot pass silently", () => {
    expect(migrationFiles().length).toBeGreaterThan(0);
  });

  it.each(migrationFiles())("%s starts with SQL", (file) => {
    const first = readFileSync(file, "utf8")
      .split("\n")
      .map((line) => line.trim())
      .find((line) => line.length > 0);

    expect(first ?? "").toMatch(sqlStart);
  });

  it.each(migrationFiles())("%s carries no tool banner on any line", (file) => {
    // The banner names the connection target, so it would also leak a host into
    // version control if one ever reached a later line.
    expect(readFileSync(file, "utf8")).not.toMatch(/^Prisma target:/mu);
  });
});
