export const serviceNames = ["web", "worker"] as const;

export {
  analysisContractArtifacts,
  analysisArtifactLifecycles,
  analysisModelRequested,
  analysisPromptText,
  analysisPromptVersion,
  analysisSchemaVersion,
  analysisTaxonomy,
  analysisValidationCodes,
  completePostCreativeAnalysisV1,
  createAnalysisInstruction,
  postCreativeAnalysisModelResponseJsonSchema,
  postCreativeAnalysisModelResponseV1Schema,
  postCreativeAnalysisV1Schema,
  validatePostCreativeAnalysisV1,
  type AnalysisObservation,
  type AnalysisArtifactLifecycle,
  type AnalysisValidationCode,
  type AnalysisValidationContext,
  type AnalysisValidationIssue,
  type AnalysisValidationResult,
  type PostCreativeAnalysisModelResponseV1,
  type PostCreativeAnalysisV1,
} from "./analysis-contract.js";

export {
  analyticsVersion,
  calculateDerivedMetric,
  calculateDerivedMetrics,
  createMetricInputs,
  derivedMetricDefinitions,
  derivedMetrics,
  derivedMetricUnavailabilityReasons,
  derivedMetricUnits,
  metricDurationSources,
  metricDurationToleranceSeconds,
  metricInputKeys,
  metricValueSources,
  resolveMetricDuration,
  type DerivedMetric,
  type DerivedMetricDefinition,
  type DerivedMetricResult,
  type DerivedMetricUnavailabilityReason,
  type DerivedMetricUnit,
  type MetricDurationResolution,
  type MetricDurationSource,
  type MetricInputKey,
  type MetricInputSet,
  type MetricInputState,
  type MetricValueSource,
} from "./analytics-metrics.js";

export {
  cohortKinds,
  cohortSelectionVersion,
  cohortUnavailabilityReasons,
  compareToBaseline,
  createCohortFingerprint,
  excludeFocalPost,
  median,
  recentCohortDays,
  recentCohortPostLimit,
  selectComparableSnapshot,
  selectComparableSnapshots,
  snapshotAgeWindowFor,
  snapshotAgeWindows,
  summariseCoverage,
  summariseSpread,
  type BaselineComparison,
  type CohortCoverage,
  type CohortDefinition,
  type CohortFingerprintInput,
  type CohortKind,
  type CohortSpread,
  type CohortUnavailabilityReason,
  type ComparableSnapshotCandidate,
  type SnapshotAgeWindow,
  type SnapshotAgeWindowKey,
} from "./analytics-cohorts.js";

export {
  benjaminiHochberg,
  bootstrapMedianDifference,
  bootstrapResamples,
  calculateFeatureStatistic,
  classificationReasons,
  confidenceClasses,
  createBootstrapSeed,
  durationBandFor,
  durationBands,
  evaluateSensitivity,
  falseDiscoveryRate,
  maximumMissingRatio,
  minimumPublicationDates,
  practicalEffectThreshold,
  sampleThresholds,
  statisticsVersion,
  topContributorShare,
  type BootstrapInterval,
  type ClassificationReason,
  type ConfidenceClass,
  type DurationBandKey,
  type FeatureComparisonInput,
  type FeatureStatistic,
  type SensitivityResult,
} from "./analytics-statistics.js";

export {
  analysisIneligibilityReasons,
  analysisRunKey,
  createAnalysisRequestSignature,
  evaluateAnalysisEligibility,
  extractAnalysisFeatures,
  isAnalyticsEligible,
  type AnalysisEligibility,
  type AnalysisEligibilityInput,
  type AnalysisFeatureColumns,
  type AnalysisIneligibilityReason,
  type AnalysisRequestInputs,
} from "./analysis-request.js";

export {
  classifyGeminiCandidate,
  classifyGeminiFileState,
  classifyGeminiResponse,
  geminiCandidateOutcomes,
  geminiFileStates,
  geminiResponseClasses,
  isGeminiFileName,
  parseGeminiRetryAfterMs,
  readGeminiUsage,
  type GeminiCandidateOutcome,
  type GeminiFileState,
  type GeminiResponseClass,
  type GeminiUsage,
} from "./gemini-response.js";

export {
  evaluateGoogleOidcProfile,
  isAllowedRequestOrigin,
  oidcDenialReasons,
  resolveSafeReturnUrl,
  type GoogleOidcDecision,
  type GoogleOidcIdentity,
  type OidcDenialReason,
} from "./auth.js";
export {
  buildInstagramRedirectUri,
  createInstagramAuthorizationRequest,
  evaluateInstagramCallback,
  evaluateInstagramGrantedScopes,
  instagramApiVersion,
  instagramAuthorizeUrl,
  instagramConnectionDenialReasons,
  instagramEligibleAccountTypes,
  instagramGraphHost,
  instagramPkceSupported,
  instagramRequiredScopes,
  instagramStateByteLength,
  instagramStateCookieName,
  instagramStateLifetimeSeconds,
  instagramTokenUrl,
  isEligibleInstagramAccountType,
  isValidInstagramRedirectUri,
  openInstagramState,
  resolveTokenExpiry,
  sealInstagramState,
  type InstagramAccountType,
  type InstagramAuthorizationRequest,
  type InstagramCallbackDecision,
  type InstagramConnectionDenialReason,
  type InstagramSealedState,
  type InstagramStateRecord,
} from "./instagram-oauth.js";
export {
  classifyInstagramMedia,
  classifyInstagramResponse,
  hashInstagramMediaPayload,
  instagramBootstrapHorizonDays,
  instagramEphemeralUrlFields,
  instagramMaximumSyncPages,
  instagramMediaFields,
  instagramMediaKinds,
  instagramMediaPageSize,
  instagramMediaRejectionReasons,
  instagramReelProductType,
  instagramResponseClasses,
  instagramSyncTriggers,
  instagramUsageHeaders,
  normaliseInstagramMediaItem,
  parseInstagramRetryAfterMs,
  parseInstagramTimestamp,
  readInstagramMediaPage,
  summariseInstagramUsage,
  type InstagramMediaKind,
  type InstagramMediaNormalisation,
  type InstagramMediaPage,
  type InstagramMediaRejectionReason,
  type InstagramResponseClass,
  type InstagramSyncTrigger,
  type InstagramUsageObservation,
  type NormalisedInstagramMedia,
} from "./instagram-media.js";
export {
  instagramAccountSyncIntervalHours,
  instagramIncrementalOverlapDays,
  instagramManualSyncKey,
  instagramScheduledSyncKey,
  instagramSnapshotDueFor,
  instagramSnapshotKey,
  instagramSyncPriority,
  instagramSyncTriggerFromKey,
  isSafeSchedulingKey,
  type InstagramSnapshotDue,
} from "./instagram-scheduling.js";
export {
  hashInstagramInsightObservations,
  instagramCanonicalMetrics,
  instagramFailedGroupObservations,
  instagramGroupFailureAvailability,
  instagramInsightCapabilityMap,
  instagramInsightGroups,
  instagramInsightRejectionReasons,
  instagramMetricAvailabilityStates,
  instagramMetricUnits,
  instagramRequestedMetrics,
  instagramSnapshotBucketFor,
  instagramSnapshotBuckets,
  instagramUnrequestedObservations,
  normaliseInstagramInsightItem,
  readInstagramInsightGroup,
  type InstagramCanonicalMetric,
  type InstagramInsightGroup,
  type InstagramInsightNormalisation,
  type InstagramInsightRejectionReason,
  type InstagramMetricAvailability,
  type InstagramMetricDefinition,
  type InstagramMetricObservation,
  type InstagramMetricUnit,
  type InstagramSnapshotBucket,
} from "./instagram-insights.js";
export {
  classifyInstagramTokenResponse,
  evaluateInstagramTokenHealth,
  instagramConnectionBlocked,
  instagramRefreshTokenUrl,
  instagramTokenExpiryWarningDays,
  instagramTokenFailures,
  instagramTokenHealthStates,
  instagramTokenLifetimeDays,
  instagramTokenRefreshDueDays,
  instagramTokenRefreshGrantType,
  instagramTokenRefreshMinimumAgeSeconds,
  type InstagramTokenFailure,
  type InstagramTokenHealth,
  type InstagramTokenHealthState,
} from "./instagram-token.js";
export {
  createAvailableDashboardSection,
  dashboardAttentionPriorities,
  orderDashboardAttentionItems,
  type DashboardAction,
  type DashboardAttentionItem,
  type DashboardAttentionPriority,
  type DashboardAttentionSummary,
  type DashboardCoverageSummary,
  type DashboardIntegrationSummary,
  type DashboardMetric,
  type DashboardProcessingSummary,
  type DashboardSection,
  type DashboardStrategySummary,
  type DashboardSummary,
} from "./dashboard.js";
export {
  isQueueName,
  parseQueueJobEnvelope,
  queueDefinitions,
  queueVersionKey,
  type QueueHandler,
  type QueueHandlerContext,
  type QueueHandlerRegistration,
  type QueueJobEnvelope,
  type QueueName,
  type QueuePublisher,
  type QueuePublishResult,
  type VersionedQueue,
} from "./background-jobs.js";
export {
  assertJobTransition,
  backgroundJobStates,
  canTransitionJob,
  isSafeJobStage,
  isTerminalJobState,
  jobAttemptStates,
  terminalBackgroundJobStates,
  InvalidJobTransitionError,
  type BackgroundJobState,
  type JobAttemptState,
} from "./job-lifecycle.js";
export {
  classifyJobHandlerError,
  decideJobRetry,
  jobFailureClasses,
  JobHandlerFailure,
  jobNextActions,
  type JobFailure,
  type JobFailureClass,
  type JobNextAction,
  type JobRetryDecision,
} from "./job-retry.js";
export {
  completeStrategyV1,
  createStrategyInstruction,
  createStrategyRecommendationFingerprint,
  strategyContractArtifacts,
  strategyModelRequested,
  strategyModelResponseJsonSchema,
  strategyModelResponseV1Schema,
  strategyPromptText,
  strategyPromptVersion,
  strategySchemaVersion,
  strategyTaxonomy,
  strategyV1Schema,
  strategyValidationCodes,
  validateStrategyV1,
  type StrategyClaimDimension,
  type StrategyEvidenceClass,
  type StrategyEvidenceRole,
  type StrategyEvidenceType,
  type StrategyManifestEvidence,
  type StrategyMode,
  type StrategyModelResponseV1,
  type StrategyV1,
  type StrategyValidationCode,
  type StrategyValidationContext,
  type StrategyValidationIssue,
  type StrategyValidationResult,
} from "./strategy-contract.js";
export {
  acceptedVideoContentTypes,
  acceptedVideoFileExtensions,
  completeUploadRequestSchema,
  evaluateUploadAdmission,
  hasUniquePartNumbers,
  isAcceptedVideoContentType,
  uploadAdmissionRefusalReasons,
  videoAssetPurgeKey,
  videoAssetValidationKey,
  videoUploadCleanupKey,
  type AcceptedVideoContentType,
  type CompleteUploadRequest,
  type UploadAdmissionDecision,
  type UploadAdmissionRefusalReason,
  type UploadAdmissionRequest,
} from "./video-upload.js";

export type ServiceName = (typeof serviceNames)[number];

export const healthKinds = ["live", "ready"] as const;

export type HealthKind = (typeof healthKinds)[number];

export type ServiceHealth = Readonly<{
  service: ServiceName;
  status: "ok";
  kind: HealthKind;
  checks: Readonly<{
    configuration?: "ok";
    process?: "ok";
  }>;
  timestamp: string;
}>;

export function createServiceHealth(
  service: ServiceName,
  kind: HealthKind,
  now: Date = new Date(),
): ServiceHealth {
  return {
    service,
    status: "ok",
    kind,
    checks: kind === "live" ? { process: "ok" } : { configuration: "ok" },
    timestamp: now.toISOString(),
  };
}
